name: AJKITCHENS
favicon: null
layout_spectrum: 0.99801
typography_spectrum: 0.88972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4ecef'
    - '#6c6e6b'
    - '#383836'
    - '#c4c3bf'
    - '#a39686'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
